# Generated by Django 5.2.9 on 2026-09-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0029_alter_historicalcourseoverview_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='other_course_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='other_course_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
