name: Tutor Build Action Test

on:
  push:
    branches:
      - 'vue/PADV-317'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Build Image
        uses: pearson-advance/tutor-build-image-action@0.0.2.alpha
        with:
          python-version: '3.8'
          tutor-version: '15'
          image-to-be-built: 'openedx'
          repository-name: 'pearsonopenedxops'
          image-name: 'tutor-test'
          image-tag: '0.0.2'
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          token: ${{ secrets.DOCKERHUB_TOKEN }}
