name: ci

on:
  push:
    branches:
      - 'vue/PADV-317'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Tutor
        run: pip install "tutor[14]"

      - name: Render templates
        run: tutor config save

      # - name: Build docker image
      #   run: tutor images build openedx

      # - name: New image name
      #   run: docker tag overhangio/openedx:15.2.0 pearsonopenedxops/tutor-test:1.0.0

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Push docker image
      #   run: docker push pearsonopenedxops/tutor-test:1.0.0
