name: ci

on:
  workflow_dispatch:
    inputs:
      tutor_version:
        description: 'Tutor version'
        required: false
        default: '15'
      build_image:
        description: 'Build image'
        required: true
      image_tag:
        description: 'Image tag (e.g., tutor-test:1.0.0)'
        required: false
        default: 'tutor-test:latest'
      repository_name:
        description: 'Repository name'
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Create and activate the env
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install Tutor
        run: pip install tutor==${{ github.event.inputs.tutor_version }}

      - name: Render templates
        run: tutor config save

      # - name: Build docker image
      #   run: |
      #     tutor images build openedx \
      #         --build-arg BUILDKIT_INLINE_CACHE=1 \
      #         --docker-arg --tag="${{ github.event.inputs.repository_name }}/${{ github.event.inputs.image_tag }}"

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Push docker image
      #   run: docker push ${{ github.event.inputs.repository_name }}/${{ github.event.inputs.image_tag }}