name: ci

on:
  push:
    branches:
      - 'vue/PADV-317'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Tutor
        run: pip install "tutor[full]"

      - name: Render templates
        run: tutor config save

      # - name: Build docker image
      #   run: tutor images build openedx

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     push: true
      #     tags: user/app:latest