name: Tutor Build Action Test

on:
  push:
    branches:
      - 'vue/PADV-317'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      # - name: Build Image
      #   uses: pearson-advance/tutor-build-image-action@0.0.1.alpha
      #   with:
      #     python-version: '3.8'
      #     tutor-version: '15.3.0'
      #     image-to-be-built: 'openedx'
      #     repository-name: 'pearsonopenedxops'
      #     image-name: 'tutor-test'
      #     image-tag: '0.0.2'
      #     docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     docker-token: ${{ secrets.DOCKERHUB_TOKEN }}
      #     private-repository: 'Pearson-Advance/pearson-core.git'
      #     theme-repository: 'Pearson-Advance/openedx-themes.git'
      #     github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Create and activate the env
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install Tutor
        run: pip install tutor=='15.3.0'

      - name: Install extra requirements
        run: |
          $extra-requirements="false"
          if [ $extra-requirements == false ]; then
            eccho "No extra requirements to be installed"
          else
            repositories=${{ secrets.REPOSITORIES }}
            for repository in "${repositories[@]}"; do
              git clone https://${{ secrets.GH_PAT }}@github.com/$repository.git \
                "$(tutor config printroot)/env/build/openedx/requirements/$repository"
              echo "-e ./$repository" >> "$(tutor config printroot)/env/build/openedx/requirements/private.txt"
              echo "Cloned "$repository" repository successfully."
            done
          fi

      - name: Install themes
        run: |
          theme-repository="false"
          if [ $theme-repository == false ]; then
            echo "No theme repository to be cloned"
          else
            git clone https://github.com/Pearson-Advanced/openedx-themes.git \
              "$(tutor config printroot)/env/build/openedx/themes/myopenedxtheme"
          fi

      # - name: Render Tutor Templates
      #   run: tutor config save

      # - name: Build image
      #   run: |
      #     tutor images build openedx \
      #         --docker-arg --tag="pearsonopenedxops/tutor-test:0.0.4"

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Push image to DockerHub
      #   run: docker push pearsonopenedxops/tutor-test:0.0.4

