name: Tutor Build Action Test

on:
  push:
    branches:
      - 'vue/PADV-317'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      # - name: Build Image
      #   uses: pearson-advance/tutor-build-image-action@0.0.1.alpha
      #   with:
      #     python-version: '3.8'
      #     tutor-version: '15'
      #     image-to-be-built: 'openedx'
      #     repository-name: 'pearsonopenedxops'
      #     image-name: 'tutor-test'
      #     image-tag: '0.0.2'
      #     docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     docker-token: ${{ secrets.DOCKERHUB_TOKEN }}
      #     private-repository: 'Pearson-Advance/pearson-core.git'
      #     theme-repository: 'Pearson-Advance/openedx-themes.git'
      #     github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Create and activate the env
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install Tutor
        run: pip install tutor==${{ inputs.tutor-version }}

      - name: Extra requirements
        run: git clone git@github.com:open-craft/xblock-pdf.git "$(tutor config printroot)/env/build/openedx/requirements/myprivaterepo"


      # - name: Clone private repository
      #   uses: sudosubin/git-clone-action@v1
      #   with:
      #     repository: ${{ inputs.private-repository }}
      #     platform: 'github'
      #     path: "$(tutor config printroot)/env/build/openedx/requirements/myprivaterepo"

      # - name: Clone GuillaumeFalourd/formulas-training PRIVATE repository
      #   uses: GuillaumeFalourd/clone-github-repo-action@v2
      #   with:
      #     owner: 'sergivalero20'
      #     repository: 'Pearson-Advance/pearson-core.git'
      #     access-token: ${{ secrets.ACCESS_TOKEN }}

      - name: Extra requirements
        run: echo "-e ./myprivaterepo" >> "$(tutor config printroot)/env/build/openedx/requirements/private.txt"

      # - name: Clone theme repository
      #   uses: sudosubin/git-clone-action@v1
      #   with:
      #     repository: ${{ inputs.theme-repository }}
      #     platform: 'github'
      #     path: "$(tutor config printroot)/env/build/openedx/themes/myopenedxtheme"

      # - name: Render Tutor Templates
      #   run: tutor config save

      - name: Build image
        run: |
          tutor images build ${{ inputs.image-to-be-built }} \
              --docker-arg --tag="${{ inputs.repository-name }}/${{ inputs.image-name }}:${{ inputs.image-tag }}"

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ inputs.docker-username }}
      #     password: ${{ inputs.docker-token }}

      # - name: Push image to DockerHub
      #   run: docker push ${{ inputs.repository-name }}/${{ inputs.image-name }}:${{ inputs.image-tag }}

