name: Tutor Build Action Test

on:
  push:
    branches:
      - 'vue/PADV-328'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Build Image
        uses: Pearson-Advance/tutor-build-image-action@vue/PADV-328
        with:
          python-version: ${{ vars.PYTHON_VERSION }}
          tutor-version: ${{ vars.TUTOR_VERSION }}
          path-image-to-be-built: '/env/build/openedx'
          repository-name: ${{ vars.REPOSITORY_NAME }}
          image-name: ${{ vars.IMAGE_NAME }}
          image-tag: ${{ vars.IMAGE_TAG }}
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker-token: ${{ secrets.DOCKERHUB_TOKEN }}
          no-docker-cache: true
          gh-access-token: ${{ secrets.GH_PAT }}
          extra-private-requirements: true
          private-repositories: ${{ vars.PRIVATE_REPOSITORIES }}
          branches: ${{ vars.branches }}
          install-tutor-pearson-plugin: true
